const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding QuizBlitz database...");

  // ─── Categories ────────────────────────────────────────────────────────────
  const categories = await Promise.all([
    prisma.category.upsert({ where: { slug: "programming_fundamentals" }, update: {}, create: { name: "Programming Fundamentals", slug: "programming_fundamentals", icon: "💻", color: "#6366f1" } }),
    prisma.category.upsert({ where: { slug: "web_development" }, update: {}, create: { name: "Web Development", slug: "web_development", icon: "🌐", color: "#0ea5e9" } }),
    prisma.category.upsert({ where: { slug: "databases" }, update: {}, create: { name: "Databases", slug: "databases", icon: "🗄️", color: "#f59e0b" } }),
    prisma.category.upsert({ where: { slug: "data_structures_algorithms" }, update: {}, create: { name: "Data Structures & Algorithms", slug: "data_structures_algorithms", icon: "🔧", color: "#10b981" } }),
    prisma.category.upsert({ where: { slug: "cybersecurity" }, update: {}, create: { name: "Cybersecurity", slug: "cybersecurity", icon: "🔒", color: "#ef4444" } }),
    prisma.category.upsert({ where: { slug: "cloud_devops" }, update: {}, create: { name: "Cloud & DevOps", slug: "cloud_devops", icon: "☁️", color: "#8b5cf6" } }),
    prisma.category.upsert({ where: { slug: "ai_machine_learning" }, update: {}, create: { name: "AI & Machine Learning", slug: "ai_machine_learning", icon: "🤖", color: "#f97316" } }),
    prisma.category.upsert({ where: { slug: "mobile_development" }, update: {}, create: { name: "Mobile Development", slug: "mobile_development", icon: "📱", color: "#06b6d4" } }),
    prisma.category.upsert({ where: { slug: "developer_tools" }, update: {}, create: { name: "Developer Tools & Practices", slug: "developer_tools", icon: "🛠️", color: "#84cc16" } }),
    prisma.category.upsert({ where: { slug: "cs_theory" }, update: {}, create: { name: "Computer Science Theory", slug: "cs_theory", icon: "🖥️", color: "#ec4899" } }),
  ]);

  const [progFund, webDev, databases, dsa, security, cloudDevops, aiMl, mobile, devTools, csTheory] = categories;

  // ─── Questions helper ──────────────────────────────────────────────────────
  async function createQuestion(data) {
    const { options, ...rest } = data;
    const existing = await prisma.question.findFirst({ where: { questionText: rest.questionText } });
    if (existing) return;
    await prisma.question.create({
      data: { ...rest, options: { create: options } },
    });
  }

  // ─── Programming Fundamentals ──────────────────────────────────────────────
  await createQuestion({ categoryId: progFund.id, subTopic: "javascript", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "What does `typeof null` return in JavaScript?", explanation: "This is a well-known JavaScript quirk — typeof null returns 'object' due to a bug in the original JS implementation.", referenceUrl: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof", tags: ["javascript", "types"], options: [{ optionText: '"null"', isCorrect: false }, { optionText: '"undefined"', isCorrect: false }, { optionText: '"object"', isCorrect: true }, { optionText: '"boolean"', isCorrect: false }] });
  await createQuestion({ categoryId: progFund.id, subTopic: "oop", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "Which of the following is NOT a pillar of Object-Oriented Programming?", explanation: "The four pillars of OOP are Encapsulation, Inheritance, Polymorphism, and Abstraction. Compilation is a build process, not an OOP concept.", tags: ["oop", "concepts"], options: [{ optionText: "Encapsulation", isCorrect: false }, { optionText: "Inheritance", isCorrect: false }, { optionText: "Compilation", isCorrect: true }, { optionText: "Polymorphism", isCorrect: false }] });
  await createQuestion({ categoryId: progFund.id, subTopic: "functional", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What does a pure function guarantee?", explanation: "A pure function always returns the same output for the same input and has no side effects (doesn't modify external state).", tags: ["functional", "pure-functions"], options: [{ optionText: "It runs faster than regular functions", isCorrect: false }, { optionText: "Same input always produces same output, with no side effects", isCorrect: true }, { optionText: "It uses no variables", isCorrect: false }, { optionText: "It cannot call other functions", isCorrect: false }] });
  await createQuestion({ categoryId: progFund.id, subTopic: "javascript", difficulty: "HARD", type: "CODE_OUTPUT", questionText: "What is the output of: console.log(0.1 + 0.2 === 0.3)?", explanation: "Due to floating-point precision in binary arithmetic, 0.1 + 0.2 = 0.30000000000000004, which is NOT equal to 0.3.", referenceUrl: "https://floating-point-gui.de/", tags: ["javascript", "floating-point"], options: [{ optionText: "true", isCorrect: false }, { optionText: "false", isCorrect: true }, { optionText: "NaN", isCorrect: false }, { optionText: "undefined", isCorrect: false }] });
  await createQuestion({ categoryId: progFund.id, subTopic: "scope", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What is a closure in programming?", explanation: "A closure is a function that retains access to its outer lexical scope even when the function is executed outside that scope.", tags: ["closures", "scope", "javascript"], options: [{ optionText: "A function that cannot be called more than once", isCorrect: false }, { optionText: "A function that has access to its outer scope even when called outside it", isCorrect: true }, { optionText: "A locked variable that cannot be reassigned", isCorrect: false }, { optionText: "A class with private properties", isCorrect: false }] });
  await createQuestion({ categoryId: progFund.id, subTopic: "memory", difficulty: "HARD", type: "MULTIPLE_CHOICE", questionText: "Which memory area stores local variables and function call frames?", explanation: "The stack stores local variables, function parameters, and return addresses. The heap is used for dynamically allocated objects.", tags: ["memory", "stack", "heap"], options: [{ optionText: "Heap", isCorrect: false }, { optionText: "Stack", isCorrect: true }, { optionText: "Code segment", isCorrect: false }, { optionText: "BSS segment", isCorrect: false }] });

  // ─── Web Development ───────────────────────────────────────────────────────
  await createQuestion({ categoryId: webDev.id, subTopic: "http", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "Which HTTP status code means 'Resource Not Found'?", explanation: "404 is the standard HTTP response code for when the server cannot find the requested resource.", referenceUrl: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404", tags: ["http", "status-codes"], options: [{ optionText: "401", isCorrect: false }, { optionText: "403", isCorrect: false }, { optionText: "500", isCorrect: false }, { optionText: "404", isCorrect: true }] });
  await createQuestion({ categoryId: webDev.id, subTopic: "react", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "In React, which hook is used to perform side effects?", explanation: "useEffect runs after render and is used for side effects like data fetching, subscriptions, or manually changing the DOM.", referenceUrl: "https://react.dev/reference/react/useEffect", tags: ["react", "hooks"], options: [{ optionText: "useState", isCorrect: false }, { optionText: "useEffect", isCorrect: true }, { optionText: "useContext", isCorrect: false }, { optionText: "useReducer", isCorrect: false }] });
  await createQuestion({ categoryId: webDev.id, subTopic: "css", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What does the CSS property `position: sticky` do?", explanation: "sticky positioning is treated as relative until the element crosses a specified threshold, then treated as fixed within its scroll container.", referenceUrl: "https://developer.mozilla.org/en-US/docs/Web/CSS/position", tags: ["css", "positioning"], options: [{ optionText: "Fixes element permanently to viewport", isCorrect: false }, { optionText: "Positions element relative to nearest scrolling ancestor until threshold", isCorrect: true }, { optionText: "Removes element from normal document flow", isCorrect: false }, { optionText: "Same as position: fixed", isCorrect: false }] });
  await createQuestion({ categoryId: webDev.id, subTopic: "javascript", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What is the difference between `==` and `===` in JavaScript?", explanation: "`==` performs type coercion before comparing; `===` checks both value AND type without coercion (strict equality).", tags: ["javascript", "operators"], options: [{ optionText: "There is no difference", isCorrect: false }, { optionText: "`==` compares value and type; `===` only compares value", isCorrect: false }, { optionText: "`===` compares value and type; `==` performs type coercion first", isCorrect: true }, { optionText: "`===` is used only for strings", isCorrect: false }] });
  await createQuestion({ categoryId: webDev.id, subTopic: "html", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "Which HTML tag defines the largest heading?", explanation: "<h1> is the largest and most important heading. There are six levels: h1 through h6, decreasing in size.", tags: ["html", "semantics"], options: [{ optionText: "<heading>", isCorrect: false }, { optionText: "<h6>", isCorrect: false }, { optionText: "<h1>", isCorrect: true }, { optionText: "<header>", isCorrect: false }] });
  await createQuestion({ categoryId: webDev.id, subTopic: "rest", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "Which HTTP method is idempotent AND safe?", explanation: "GET is both safe (no side effects) and idempotent (multiple identical requests have the same effect). POST is neither; PUT is idempotent but not safe.", tags: ["http", "rest", "methods"], options: [{ optionText: "POST", isCorrect: false }, { optionText: "PUT", isCorrect: false }, { optionText: "GET", isCorrect: true }, { optionText: "PATCH", isCorrect: false }] });
  await createQuestion({ categoryId: webDev.id, subTopic: "javascript", difficulty: "HARD", type: "CODE_OUTPUT", questionText: "What does this code output? `console.log([] + [])`", explanation: "[] coerces to an empty string ''. '' + '' = ''. So the output is an empty string (printed as nothing visible but it's '').", tags: ["javascript", "type-coercion"], options: [{ optionText: "[]", isCorrect: false }, { optionText: "0", isCorrect: false }, { optionText: '""  (empty string)', isCorrect: true }, { optionText: "undefined", isCorrect: false }] });

  // ─── Databases ─────────────────────────────────────────────────────────────
  await createQuestion({ categoryId: databases.id, subTopic: "transactions", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "What does ACID stand for in database transactions?", explanation: "ACID ensures reliable processing: Atomicity (all-or-nothing), Consistency (data stays valid), Isolation (concurrent transactions don't interfere), Durability (committed data persists).", tags: ["acid", "transactions"], options: [{ optionText: "Atomicity, Consistency, Isolation, Durability", isCorrect: true }, { optionText: "Accuracy, Concurrency, Integrity, Data", isCorrect: false }, { optionText: "Atomicity, Concurrency, Index, Durability", isCorrect: false }, { optionText: "Access, Consistency, Isolation, Distribution", isCorrect: false }] });
  await createQuestion({ categoryId: databases.id, subTopic: "sql", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "Which SQL JOIN returns only rows that have matching values in BOTH tables?", explanation: "INNER JOIN returns only the rows where there's a match in both the left and right table.", tags: ["sql", "joins"], options: [{ optionText: "LEFT JOIN", isCorrect: false }, { optionText: "FULL OUTER JOIN", isCorrect: false }, { optionText: "INNER JOIN", isCorrect: true }, { optionText: "CROSS JOIN", isCorrect: false }] });
  await createQuestion({ categoryId: databases.id, subTopic: "nosql", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "Redis is primarily what type of database?", explanation: "Redis is an in-memory key-value store, often used for caching, session management, and real-time leaderboards.", tags: ["redis", "nosql", "key-value"], options: [{ optionText: "Document store", isCorrect: false }, { optionText: "Relational", isCorrect: false }, { optionText: "Key-Value store", isCorrect: true }, { optionText: "Graph database", isCorrect: false }] });
  await createQuestion({ categoryId: databases.id, subTopic: "theory", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What does the CAP theorem state about distributed systems?", explanation: "CAP theorem states a distributed system can only guarantee 2 of 3: Consistency (all nodes see same data), Availability (every request gets a response), Partition tolerance (system works despite network splits).", tags: ["cap-theorem", "distributed"], options: [{ optionText: "You can have Consistency, Availability, and Partition tolerance simultaneously", isCorrect: false }, { optionText: "A distributed system can only guarantee 2 of: Consistency, Availability, Partition tolerance", isCorrect: true }, { optionText: "Partition tolerance is always optional", isCorrect: false }, { optionText: "Consistency and Availability are always mutually exclusive", isCorrect: false }] });
  await createQuestion({ categoryId: databases.id, subTopic: "sql", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What SQL keyword is used to filter rows AFTER grouping?", explanation: "HAVING filters groups after GROUP BY, whereas WHERE filters rows before grouping.", tags: ["sql", "grouping"], options: [{ optionText: "WHERE", isCorrect: false }, { optionText: "FILTER", isCorrect: false }, { optionText: "HAVING", isCorrect: true }, { optionText: "LIMIT", isCorrect: false }] });
  await createQuestion({ categoryId: databases.id, subTopic: "indexing", difficulty: "HARD", type: "MULTIPLE_CHOICE", questionText: "What is a covering index in databases?", explanation: "A covering index includes all the columns needed by a query, allowing the DB engine to satisfy the query entirely from the index without reading the table rows.", tags: ["indexing", "performance"], options: [{ optionText: "An index that covers the entire table", isCorrect: false }, { optionText: "An index that includes all columns needed by a query, avoiding table lookups", isCorrect: true }, { optionText: "An index automatically created by the database", isCorrect: false }, { optionText: "A foreign key constraint index", isCorrect: false }] });

  // ─── DSA ───────────────────────────────────────────────────────────────────
  await createQuestion({ categoryId: dsa.id, subTopic: "algorithms", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "What is the time complexity of binary search?", explanation: "Binary search halves the search space each iteration, giving O(log n) time complexity.", tags: ["binary-search", "big-o"], options: [{ optionText: "O(n)", isCorrect: false }, { optionText: "O(n²)", isCorrect: false }, { optionText: "O(log n)", isCorrect: true }, { optionText: "O(1)", isCorrect: false }] });
  await createQuestion({ categoryId: dsa.id, subTopic: "data-structures", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "Which data structure uses LIFO (Last In, First Out)?", explanation: "A Stack follows LIFO — the last element pushed is the first to be popped, like a stack of plates.", tags: ["stack", "lifo"], options: [{ optionText: "Queue", isCorrect: false }, { optionText: "Stack", isCorrect: true }, { optionText: "Linked List", isCorrect: false }, { optionText: "Tree", isCorrect: false }] });
  await createQuestion({ categoryId: dsa.id, subTopic: "big-o", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "In Big O notation, which complexity is the most efficient?", explanation: "O(1) is constant time — regardless of input size, it always takes the same time. O(n log n) and O(n) grow with input size.", tags: ["big-o", "complexity"], options: [{ optionText: "O(n log n)", isCorrect: false }, { optionText: "O(n²)", isCorrect: false }, { optionText: "O(n)", isCorrect: false }, { optionText: "O(1)", isCorrect: true }] });
  await createQuestion({ categoryId: dsa.id, subTopic: "sorting", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What is the average-case time complexity of QuickSort?", explanation: "QuickSort has O(n log n) average-case complexity. Worst-case (already sorted, bad pivot) is O(n²), but this is rare with good pivot selection.", tags: ["quicksort", "sorting", "big-o"], options: [{ optionText: "O(n²)", isCorrect: false }, { optionText: "O(n log n)", isCorrect: true }, { optionText: "O(n)", isCorrect: false }, { optionText: "O(log n)", isCorrect: false }] });
  await createQuestion({ categoryId: dsa.id, subTopic: "trees", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What property defines a Binary Search Tree (BST)?", explanation: "In a BST, all nodes in the left subtree have values less than the root, and all nodes in the right subtree have values greater than the root.", tags: ["bst", "trees"], options: [{ optionText: "Each node has exactly 2 children", isCorrect: false }, { optionText: "Left child < parent < right child for all nodes", isCorrect: true }, { optionText: "The tree is always balanced", isCorrect: false }, { optionText: "Values are stored in insertion order", isCorrect: false }] });
  await createQuestion({ categoryId: dsa.id, subTopic: "graphs", difficulty: "HARD", type: "MULTIPLE_CHOICE", questionText: "What is the space complexity of Breadth-First Search (BFS)?", explanation: "BFS uses a queue and in the worst case must store all nodes at the widest level. In a complete binary tree that's O(n/2) ≈ O(n). In general graphs it's O(V) where V is vertices.", tags: ["bfs", "graphs", "complexity"], options: [{ optionText: "O(1)", isCorrect: false }, { optionText: "O(log n)", isCorrect: false }, { optionText: "O(n)", isCorrect: true }, { optionText: "O(n²)", isCorrect: false }] });

  // ─── Cybersecurity ─────────────────────────────────────────────────────────
  await createQuestion({ categoryId: security.id, subTopic: "attacks", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "What type of attack injects malicious scripts into web pages viewed by other users?", explanation: "XSS (Cross-Site Scripting) allows attackers to inject client-side scripts into web pages. Unlike CSRF, it targets other users, not the server.", tags: ["xss", "attacks"], options: [{ optionText: "CSRF", isCorrect: false }, { optionText: "SQL Injection", isCorrect: false }, { optionText: "XSS (Cross-Site Scripting)", isCorrect: true }, { optionText: "DDoS", isCorrect: false }] });
  await createQuestion({ categoryId: security.id, subTopic: "cryptography", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "What is the main difference between hashing and encryption?", explanation: "Encryption is reversible (you can decrypt with the key). Hashing is a one-way function — you cannot recover the original input from a hash.", tags: ["hashing", "encryption", "cryptography"], options: [{ optionText: "Hashing is reversible, encryption is not", isCorrect: false }, { optionText: "Encryption is reversible with a key, hashing is one-way", isCorrect: true }, { optionText: "They are the same process", isCorrect: false }, { optionText: "Hashing uses keys, encryption does not", isCorrect: false }] });
  await createQuestion({ categoryId: security.id, subTopic: "web-security", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "Which HTTP header helps prevent clickjacking attacks?", explanation: "X-Frame-Options prevents your page from being embedded in an iframe, stopping clickjacking attacks. Content-Security-Policy's frame-ancestors directive is the modern replacement.", tags: ["headers", "clickjacking"], options: [{ optionText: "Content-Type", isCorrect: false }, { optionText: "X-Frame-Options", isCorrect: true }, { optionText: "Authorization", isCorrect: false }, { optionText: "Cache-Control", isCorrect: false }] });
  await createQuestion({ categoryId: security.id, subTopic: "auth", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What does JWT stand for, and what is it used for?", explanation: "JSON Web Token is a compact, URL-safe token format used for stateless authentication. It contains claims encoded as JSON and is signed to prevent tampering.", tags: ["jwt", "authentication"], options: [{ optionText: "Java Web Transfer — used to move data between Java services", isCorrect: false }, { optionText: "JSON Web Token — used for stateless authentication", isCorrect: true }, { optionText: "JavaScript Web Template — used for rendering pages", isCorrect: false }, { optionText: "JSON Wrapper Type — used for API responses", isCorrect: false }] });
  await createQuestion({ categoryId: security.id, subTopic: "attacks", difficulty: "HARD", type: "MULTIPLE_CHOICE", questionText: "What is a timing attack in cryptography?", explanation: "A timing attack exploits the variation in execution time of cryptographic operations to deduce secret information, such as private keys or password hashes.", tags: ["timing-attack", "cryptography", "side-channel"], options: [{ optionText: "An attack that waits for the system to be idle before striking", isCorrect: false }, { optionText: "An attack exploiting execution time variations to infer secret data", isCorrect: true }, { optionText: "An attack synchronizing packets with server clock", isCorrect: false }, { optionText: "A replay attack using time-stamped tokens", isCorrect: false }] });
  await createQuestion({ categoryId: security.id, subTopic: "sql-injection", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "Which of the following best prevents SQL injection?", explanation: "Parameterized queries (prepared statements) separate SQL code from data, preventing attackers from injecting SQL. Input sanitization alone is insufficient.", tags: ["sql-injection", "prevention"], options: [{ optionText: "Encrypting the database", isCorrect: false }, { optionText: "Using parameterized queries / prepared statements", isCorrect: true }, { optionText: "Hiding the database port", isCorrect: false }, { optionText: "Using a strong password", isCorrect: false }] });

  // ─── Cloud & DevOps ────────────────────────────────────────────────────────
  await createQuestion({ categoryId: cloudDevops.id, subTopic: "docker", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "What is the difference between a Docker image and a Docker container?", explanation: "An image is a read-only template (the blueprint). A container is a running instance of that image — like a class vs an object in OOP.", tags: ["docker", "containers"], options: [{ optionText: "They are the same thing", isCorrect: false }, { optionText: "An image is running; a container is a template", isCorrect: false }, { optionText: "An image is a template; a container is a running instance", isCorrect: true }, { optionText: "Containers are only used on Linux", isCorrect: false }] });
  await createQuestion({ categoryId: cloudDevops.id, subTopic: "kubernetes", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "In Kubernetes, what is a Pod?", explanation: "A Pod is the smallest deployable unit in Kubernetes. It can contain one or more containers that share network and storage resources.", tags: ["kubernetes", "pods"], options: [{ optionText: "A virtual machine", isCorrect: false }, { optionText: "The smallest deployable unit, containing one or more containers", isCorrect: true }, { optionText: "A networking layer", isCorrect: false }, { optionText: "A persistent storage volume", isCorrect: false }] });
  await createQuestion({ categoryId: cloudDevops.id, subTopic: "cicd", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "What does CI/CD stand for?", explanation: "CI = Continuous Integration (automatically build/test on every commit). CD = Continuous Delivery/Deployment (automatically deliver to production or staging).", tags: ["cicd", "devops"], options: [{ optionText: "Code Integration / Code Deployment", isCorrect: false }, { optionText: "Continuous Integration / Continuous Delivery or Deployment", isCorrect: true }, { optionText: "Container Infrastructure / Container Delivery", isCorrect: false }, { optionText: "Central Index / Central Database", isCorrect: false }] });
  await createQuestion({ categoryId: cloudDevops.id, subTopic: "docker", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What is the difference between CMD and ENTRYPOINT in a Dockerfile?", explanation: "ENTRYPOINT defines the main executable that always runs. CMD provides default arguments to ENTRYPOINT or the default command. CMD can be overridden at runtime; ENTRYPOINT cannot (unless --entrypoint flag is used).", tags: ["docker", "dockerfile"], options: [{ optionText: "They are identical", isCorrect: false }, { optionText: "CMD runs first; ENTRYPOINT runs after", isCorrect: false }, { optionText: "ENTRYPOINT is the main executable; CMD provides default args that can be overridden", isCorrect: true }, { optionText: "ENTRYPOINT is optional; CMD is required", isCorrect: false }] });
  await createQuestion({ categoryId: cloudDevops.id, subTopic: "cloud", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "What does IaaS stand for?", explanation: "Infrastructure as a Service provides virtualized computing resources over the internet (VMs, storage, networking). Examples: AWS EC2, Google Compute Engine.", tags: ["cloud", "iaas"], options: [{ optionText: "Internet and Application Service", isCorrect: false }, { optionText: "Infrastructure as a Service", isCorrect: true }, { optionText: "Integration and Assembly Service", isCorrect: false }, { optionText: "Isolated Application and Storage", isCorrect: false }] });
  await createQuestion({ categoryId: cloudDevops.id, subTopic: "kubernetes", difficulty: "HARD", type: "MULTIPLE_CHOICE", questionText: "What causes a Kubernetes CrashLoopBackOff error?", explanation: "CrashLoopBackOff means a container starts, crashes, and Kubernetes keeps trying to restart it with exponential backoff. Causes include bad config, missing env vars, or application errors.", tags: ["kubernetes", "debugging"], options: [{ optionText: "The cluster ran out of memory", isCorrect: false }, { optionText: "A container keeps crashing and Kubernetes repeatedly restarts it with backoff", isCorrect: true }, { optionText: "The Pod has no network access", isCorrect: false }, { optionText: "The image was not found in the registry", isCorrect: false }] });

  // ─── AI & Machine Learning ─────────────────────────────────────────────────
  await createQuestion({ categoryId: aiMl.id, subTopic: "concepts", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "Which Python library is primarily used for data manipulation and analysis?", explanation: "Pandas provides DataFrame structures for data manipulation. NumPy is for numerical arrays, Matplotlib for visualization, scikit-learn for ML models.", tags: ["python", "pandas", "data-science"], options: [{ optionText: "NumPy", isCorrect: false }, { optionText: "Matplotlib", isCorrect: false }, { optionText: "Pandas", isCorrect: true }, { optionText: "Scikit-learn", isCorrect: false }] });
  await createQuestion({ categoryId: aiMl.id, subTopic: "ml-concepts", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "What is 'overfitting' in machine learning?", explanation: "Overfitting occurs when a model learns the training data too well (including noise), causing it to perform poorly on unseen data. It has high training accuracy but low test accuracy.", tags: ["overfitting", "ml"], options: [{ optionText: "Model is too simple to learn patterns", isCorrect: false }, { optionText: "Model performs well on training data but poorly on unseen data", isCorrect: true }, { optionText: "Model takes too long to train", isCorrect: false }, { optionText: "Model uses too many features and crashes", isCorrect: false }] });
  await createQuestion({ categoryId: aiMl.id, subTopic: "llm", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What does RAG stand for in the context of AI?", explanation: "Retrieval Augmented Generation combines a retrieval system (vector search over documents) with an LLM to generate answers grounded in specific knowledge.", tags: ["rag", "llm", "ai"], options: [{ optionText: "Random Aggregate Generation", isCorrect: false }, { optionText: "Retrieval Augmented Generation", isCorrect: true }, { optionText: "Recursive Attention Graph", isCorrect: false }, { optionText: "Real-time API Gateway", isCorrect: false }] });
  await createQuestion({ categoryId: aiMl.id, subTopic: "deep-learning", difficulty: "HARD", type: "MULTIPLE_CHOICE", questionText: "What is the vanishing gradient problem in neural networks?", explanation: "In deep networks, gradients become exponentially small as they propagate backwards through layers, making early layers train very slowly or not at all. Solved by ReLU, batch norm, residual connections, etc.", tags: ["deep-learning", "gradients", "backpropagation"], options: [{ optionText: "Gradients become too large and cause numerical overflow", isCorrect: false }, { optionText: "Gradients become exponentially small, preventing early layers from learning", isCorrect: true }, { optionText: "The model forgets previously learned information", isCorrect: false }, { optionText: "Gradient descent converges too quickly to a local minimum", isCorrect: false }] });
  await createQuestion({ categoryId: aiMl.id, subTopic: "ml-types", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "Which type of machine learning uses labeled training data?", explanation: "Supervised learning trains on labeled data (input-output pairs). Unsupervised learning finds patterns in unlabeled data. Reinforcement learning uses a reward signal.", tags: ["supervised", "ml-types"], options: [{ optionText: "Unsupervised Learning", isCorrect: false }, { optionText: "Reinforcement Learning", isCorrect: false }, { optionText: "Supervised Learning", isCorrect: true }, { optionText: "Self-Supervised Learning", isCorrect: false }] });

  // ─── Mobile Development ────────────────────────────────────────────────────
  await createQuestion({ categoryId: mobile.id, subTopic: "flutter", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "Which programming language is used to build Flutter apps?", explanation: "Flutter uses Dart, a language developed by Google. Dart is compiled to native code for performance.", tags: ["flutter", "dart"], options: [{ optionText: "JavaScript", isCorrect: false }, { optionText: "Swift", isCorrect: false }, { optionText: "Kotlin", isCorrect: false }, { optionText: "Dart", isCorrect: true }] });
  await createQuestion({ categoryId: mobile.id, subTopic: "react-native", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "What is the purpose of AsyncStorage in React Native?", explanation: "AsyncStorage is an unencrypted, asynchronous persistent storage system for simple key-value data on the device.", tags: ["react-native", "storage"], options: [{ optionText: "Making API calls asynchronously", isCorrect: false }, { optionText: "Persisting simple key-value data locally on the device", isCorrect: true }, { optionText: "Managing navigation state", isCorrect: false }, { optionText: "Rendering animations asynchronously", isCorrect: false }] });
  await createQuestion({ categoryId: mobile.id, subTopic: "flutter", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What is the difference between StatelessWidget and StatefulWidget in Flutter?", explanation: "StatelessWidget is immutable — it renders once based on its input. StatefulWidget maintains mutable State that can change over time, triggering rebuilds via setState().", tags: ["flutter", "widgets"], options: [{ optionText: "StatelessWidget is faster; StatefulWidget is slower", isCorrect: false }, { optionText: "StatelessWidget is immutable; StatefulWidget holds mutable state that can trigger rebuilds", isCorrect: true }, { optionText: "StatefulWidget can only be used for forms", isCorrect: false }, { optionText: "They are the same but StatelessWidget has fewer features", isCorrect: false }] });
  await createQuestion({ categoryId: mobile.id, subTopic: "notifications", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What does APNs stand for?", explanation: "Apple Push Notification service is Apple's platform for sending push notifications to iOS, macOS, tvOS, and watchOS devices.", tags: ["push-notifications", "ios"], options: [{ optionText: "Android Push Notification Service", isCorrect: false }, { optionText: "Apple Push Notification service", isCorrect: true }, { optionText: "Application Programming Notification System", isCorrect: false }, { optionText: "Async Process Node Service", isCorrect: false }] });

  // ─── Developer Tools & Practices ───────────────────────────────────────────
  await createQuestion({ categoryId: devTools.id, subTopic: "git", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "What is the git command to stage ALL changes for commit?", explanation: "`git add .` stages all changes in the current directory (new, modified, deleted files). `git add -A` stages all changes project-wide.", tags: ["git", "staging"], options: [{ optionText: "git commit -all", isCorrect: false }, { optionText: "git stage all", isCorrect: false }, { optionText: "git add .", isCorrect: true }, { optionText: "git push all", isCorrect: false }] });
  await createQuestion({ categoryId: devTools.id, subTopic: "git", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What does `git rebase` do?", explanation: "git rebase moves or replays your commits on top of another base commit, creating a linear history. Unlike merge, it rewrites commit history.", tags: ["git", "rebase"], options: [{ optionText: "Merges two branches with a merge commit", isCorrect: false }, { optionText: "Moves or replays commits onto another base commit, rewriting history", isCorrect: true }, { optionText: "Permanently deletes a branch", isCorrect: false }, { optionText: "Creates a new empty repository", isCorrect: false }] });
  await createQuestion({ categoryId: devTools.id, subTopic: "solid", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "What does the 'S' in SOLID principles stand for?", explanation: "S = Single Responsibility Principle: a class should have only one reason to change. This makes code easier to maintain and test.", tags: ["solid", "design-principles"], options: [{ optionText: "Separation of Concerns", isCorrect: false }, { optionText: "Single Responsibility Principle", isCorrect: true }, { optionText: "Static Typing Principle", isCorrect: false }, { optionText: "Secure Coding Standard", isCorrect: false }] });
  await createQuestion({ categoryId: devTools.id, subTopic: "semver", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "In Semantic Versioning (1.2.3), what does the MIDDLE number represent?", explanation: "In SemVer: MAJOR (breaking changes) . MINOR (new features, backwards compatible) . PATCH (bug fixes). So 1.2.3 → Minor = 2.", tags: ["semver", "versioning"], options: [{ optionText: "Patch — bug fixes", isCorrect: false }, { optionText: "Major — breaking changes", isCorrect: false }, { optionText: "Minor — new features, backwards compatible", isCorrect: true }, { optionText: "Build number", isCorrect: false }] });
  await createQuestion({ categoryId: devTools.id, subTopic: "testing", difficulty: "HARD", type: "MULTIPLE_CHOICE", questionText: "What is the difference between unit tests and integration tests?", explanation: "Unit tests test a single function/module in isolation (mocking dependencies). Integration tests verify multiple modules work together correctly.", tags: ["testing", "unit-tests", "integration-tests"], options: [{ optionText: "Unit tests are slower; integration tests are faster", isCorrect: false }, { optionText: "Unit tests test isolated units; integration tests verify multiple modules working together", isCorrect: true }, { optionText: "Integration tests require a browser; unit tests do not", isCorrect: false }, { optionText: "They are different names for the same thing", isCorrect: false }] });

  // ─── CS Theory ─────────────────────────────────────────────────────────────
  await createQuestion({ categoryId: csTheory.id, subTopic: "binary", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "How many bits are in one byte?", explanation: "1 byte = 8 bits. This is a fundamental unit of digital information.", tags: ["bits", "bytes", "binary"], options: [{ optionText: "4", isCorrect: false }, { optionText: "16", isCorrect: false }, { optionText: "8", isCorrect: true }, { optionText: "2", isCorrect: false }] });
  await createQuestion({ categoryId: csTheory.id, subTopic: "os", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "What is a 'deadlock' in operating systems?", explanation: "A deadlock occurs when two or more processes each hold a resource the other needs, with neither one able to proceed.", tags: ["deadlock", "os", "processes"], options: [{ optionText: "A process that runs forever in an infinite loop", isCorrect: false }, { optionText: "Two or more processes waiting on each other to release resources", isCorrect: true }, { optionText: "A memory overflow error", isCorrect: false }, { optionText: "A crashed thread that cannot restart", isCorrect: false }] });
  await createQuestion({ categoryId: csTheory.id, subTopic: "networking", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What layer of the OSI model does HTTP operate on?", explanation: "HTTP is an application-layer protocol — Layer 7 of the OSI model. TCP operates at Layer 4, IP at Layer 3.", referenceUrl: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview", tags: ["osi", "networking", "http"], options: [{ optionText: "Layer 3 — Network", isCorrect: false }, { optionText: "Layer 4 — Transport", isCorrect: false }, { optionText: "Layer 6 — Presentation", isCorrect: false }, { optionText: "Layer 7 — Application", isCorrect: true }] });
  await createQuestion({ categoryId: csTheory.id, subTopic: "networking", difficulty: "EASY", type: "MULTIPLE_CHOICE", questionText: "How many layers does the OSI model have?", explanation: "The OSI (Open Systems Interconnection) model has 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application.", tags: ["osi", "networking"], options: [{ optionText: "4", isCorrect: false }, { optionText: "5", isCorrect: false }, { optionText: "7", isCorrect: true }, { optionText: "9", isCorrect: false }] });
  await createQuestion({ categoryId: csTheory.id, subTopic: "concurrency", difficulty: "HARD", type: "MULTIPLE_CHOICE", questionText: "What is the difference between a mutex and a semaphore?", explanation: "A mutex (mutual exclusion) is owned by a thread and can only be released by that thread — used for exclusive access. A semaphore is a signaling mechanism with a counter — used to control access to a pool of resources.", tags: ["mutex", "semaphore", "concurrency"], options: [{ optionText: "They are the same — different names for a lock", isCorrect: false }, { optionText: "A mutex is owned by a thread (exclusive lock); a semaphore is a counter-based signaling mechanism", isCorrect: true }, { optionText: "A semaphore is faster; a mutex is more secure", isCorrect: false }, { optionText: "A mutex is used in distributed systems; a semaphore is for single-threaded programs", isCorrect: false }] });
  await createQuestion({ categoryId: csTheory.id, subTopic: "compilers", difficulty: "MEDIUM", type: "MULTIPLE_CHOICE", questionText: "What is the main difference between a compiler and an interpreter?", explanation: "A compiler translates the entire source code to machine code before execution. An interpreter translates and executes code line-by-line at runtime.", tags: ["compiler", "interpreter", "languages"], options: [{ optionText: "Compilers are faster at writing code; interpreters are faster at running it", isCorrect: false }, { optionText: "A compiler translates all code before execution; an interpreter executes line-by-line", isCorrect: true }, { optionText: "Interpreters produce compiled binaries; compilers do not", isCorrect: false }, { optionText: "They produce identical output through different means", isCorrect: false }] });

  console.log("✅ Seeding complete! Questions inserted across all 10 categories.");
}

main()
  .catch((e) => { console.error("❌ Seed failed:", e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
